### ISSUE TITLE
Artefacts

### ISSUE THREAD

**Issue by brynfury** [kode80/kode80SSR#5] opened 2015-03-23 07:14 UTC
Hi.
I tested the actual version of your SSR. With the textures enabled it looks ok. But when i disable the textures you see clearly some artefacts in the reflection. And no matter which value i change, the artefacts stay.
And another problem is, that there are reflections, where no reflections shouldn't be.
I think you know these problems and you working on this ?! Maybe a update will come in the next time?

thanks and keep up the good work..

**Comment by kode80** [comment] 2015-03-24 18:36
Could you post a screen shot of these artifacts and the SSR settings you're using?

Thanks!

**Comment by Snow-Okami** [comment] 2015-03-25 03:58
Hi Kode80,

I think I am experiencing the same thing brynfury is. Not sure why you aren't charging for this, but I would happily pay for the support.

Here are two screen shots of some artifacting I am facing. It only occurs at very specific angles and these angles are static. If you come back to an exact coordinate and then face the camera exactly at the same rotation, you will see the same artifacting :

http://gyazo.com/e329dcb1dbe428d28a96802ffc393d11

http://gyazo.com/1e19b29a032dd465046b5ae180c5a17c

Here are my settings: http://gyazo.com/0ac66850c71ba351ca7b4c7b869e64f6

At first I thought it was an incompatibility with my other post processing FX but I have gotten the same results with just SSR. Also it seems this only occurs on a semi advanced scene with texturing and many of the material channels used. On a simple scene with no textures I do not experience the issue.

Again if this is out the realm of your support just let me know how to contact you :) And truly thank you again for such an amazing solution this age old problem.

**Comment by brynfury** [comment] 2015-03-25 06:51
![ssr_artefacts](https://cloud.githubusercontent.com/assets/11438086/6819590/bdb80d8c-d2c3-11e4-8a4c-72546e1b6620.jpg)

The settings are the default of your testscene...

**Comment by antimophum** [comment] 2015-03-25 12:41
![a](https://cloud.githubusercontent.com/assets/11586142/6824662/877d8752-d2f4-11e4-96ed-4e973186c280.jpg)
![b](https://cloud.githubusercontent.com/assets/11586142/6824664/889939b0-d2f4-11e4-9a3d-ce6e106000b2.jpg)
some artefacts

**Comment by kode80** [comment] 2015-03-25 13:52
@brynfury those artifacts are caused by the pixel stride setting. The higher the pixel stride, the higher the chance of false positives (particularly with thin geometry) and that's what you're seeing in your screenshot. If you pause the game in the editor and lower the pixel stride, you'll see those false reflections start to disappear. Obviously lowering the pixel stride means you need more iterations per ray to match the reflection length (or lower the resolution of the SSR pass using the downsample setting) - so it's very much a balancing act between performance/quality based on scene.

@antimophum those artifacts are unfortunately a side effect of SSR - notice how all the missing reflections you've circled are obscured by other geometry in the scene (for example: the part of the wall that's missing in the second screenshot is obscured by the crank handle thing on the table). SSR being a screen space effect can only reflect pixels that exist in the current frame buffer. Using reflection probes can help mask these missing reflections to a degree, although the current implementation is not physically correct so depending on scene the color/brightness of probes may not match the SSR reflections 100% - this is something I'm working on.

@Snow-Okami those artifacts _are_ unusual. The closest I've seen to that has only occurred when I've had an extreme far clip plane/low FOV. If neither of those apply to your scene, could you maybe post a couple more screens of it working/not working based on camera angle and give me a few more details about your scene? Feel free to email me (address is on website kode80.com) - but I'm happy to provide support as and when I can through here. :)

**Comment by antimophum** [comment] 2015-03-25 14:10
thank good for your job!

**Comment by Snow-Okami** [comment] 2015-03-26 05:31
@kode80 I got to the bottom of the issue. It turns out the SSR is incompatible with SSAO Pro from the asset store (tried 1.3.2 as well as 1.4) Once You add SSAO it causes what is seen in my screen shots and can only be cured by completely removing the component, not just disabling it. The component must be removed from the camera and the scene started without it for the artifacts not to appear.

Not sure how I missed it the first time I tried testing that.

How unfortunate! But something told me that this wouldn't just 'work' out of the box, there are always compatibility issues between these things T.T.

Thanks again for the excellent support.

**Comment by kode80** [comment] 2015-03-26 11:22
@Snow-Okami that sucks. With this new info and based on the screens you posted - if I had to make a guess I'd say that SSAO Pro is setting the camera's depthTextureMode to DepthTextureMode.DepthNormals. You can check this by looking at the bottom of the Camera component in the editor, if it says something like "info: this camera renders depth and normals" then that's your problem. kode80SSR uses DepthTextureMode.Depth to get high precision depth (since the normals are too low precision to use reliably and world space normals are already in the GBuffer).
When you get a chance could you check if this is the case? If it is, I could either render my own depth texture or use the lower precision depth when DepthTextureMode.DepthNormals is required by another component on the camera - neither ideal but they would at least fix the compatibility.

**Comment by Snow-Okami** [comment] 2015-03-27 22:46
@kode80 Indeed that is the issue. "Info: renders Depth & DepthNormals textures"

That sounds great. I would love to be able to use these both at the same time, SSR is desperately needed by many XD. But don't go out of your way for it.

Anywho, if you do I'd be happy to donate for your efforts.

**Comment by jessyoblio** [comment] 2015-04-11 16:48
@kode80 @Snow-Okami 
I Tried to understand the cause of the artifacts... If I remove a normal map from the material, the problem remains... Maybe, the cause of that, born in the bilateralBlur shader... I will investigate. Cheers!

**Comment by jessyoblio** [comment] 2015-04-11 17:15
Yes! the problem desappear when i change the offset of 1 of 2 _CameraGBufferTexture. Exactly in lines 68 and 97 of BilateralBlur shader. It Seems the problem is caused by a sort of overlapping of the 2 Gbuffer Depth Texture. What do you think? @kode80

**Comment by Rbn3D** [comment] 2015-04-12 17:05
@jessyoblio what did you change exactly? Can you submit a PR? Thank you!

**Comment by jessyoblio** [comment] 2015-04-12 18:15
https://imagizer.imageshack.us/v2/1236x636q90/661/tMwG5Q.png

Inherent to this problem... I Can submit the modified BilateralBlur Shader, but the Max Blur Radius will not work for the GBuffer Textures... Example: If I change the offset of the _CameraGBufferTexture2 ( World space normal ) the problem disappear, but the BilateralBlur will not affect normals in this case.

**Comment by jessyoblio** [comment] 2015-04-12 19:12
OK! I'm happy to say you: Everything is ok! The problem was on the weights values ( multiples of 4 and not 3 ). Also, I have add a Quality Blur Function to SSR.cs ( more blur steps reflections ). max is 8 for now... but i will up it in another time. So... Good Work!

**Comment by jessyoblio** [comment] 2015-04-12 19:17
Where is the upload button? I'm a newbie in github... so, please, help me

**Comment by Rbn3D** [comment] 2015-04-12 20:28
@jessyoblio You must:
1: make a fork of this repo
2: Create a new branch in your forked repo
3: Push your changes to these branch
4: Make a pull request from that branch

**Comment by Rbn3D** [comment] 2015-04-12 20:32
@jessyoblio Good work btw

**Comment by jessyoblio** [comment] 2015-04-12 21:17
How to rename the branch? - Anyway, I have uploaded the files... Let us know if it works for you

**Comment by jessyoblio** [comment] 2015-04-13 11:18
Hi guys... latest news... I have changed max blur quality to 4 ( anyway with better results ), because 8 was too expensive... I will try to optimize it in another time...

Screenshots:

Quality Blur 4 - 2 with Max Roughness: 16
http://imageshack.com/a/img537/3306/AsJHFf.jpg

Problem solved:
http://imageshack.com/a/img661/6851/t5p70s.png

My FPS: from 68 to 72
FXAA 4x
Chromatic Abberration
Bloom
Tonemapping

**Comment by Rbn3D** [comment] 2015-04-13 17:14
These screens are looking very good! I will checkout and see it in my current setup...

**Comment by kode80** [comment] 2015-04-14 14:36
I'm going to try and dedicate some time this week to an update, specifically a fix for camera's that are using other components which require DepthNormals (which as mentioned by @Snow-Okami breaks kode80SSR - which uses high precision Depth only) and @jessyoblio's blur additions.

**Comment by jessyoblio** [comment] 2015-04-14 19:01
Only a clarification: SSAO Pro does not create problems with Kode80 SSR... and @kode80 The normal depth problem is ok now.

**Comment by KenzieMac130** [comment] 2015-04-23 03:45
Kode80SSR Package as of 3/17/2015.
Unity 5.0.0f3 Pro
Nvidia 840M GPU, Intel Core i7 Quad

Yes, I am also still getting some artifacts with the SSR blurring for roughness. this happens regardless of weather or not SSAO Pro or any other Post effect is active. The artifact is downsampled alongside the Blur Downsample Option. This artifact is dependent on camera orientation and doesn't appear in some situations. This doesn't really make the SSR completely broken so long as you keep Max Blur Radius to 0 it wont be a problem.

![kode80 ssr blur artifacts](https://cloud.githubusercontent.com/assets/7585719/7289896/775011e0-e944-11e4-9413-08633a2081c6.png)

![kode80 ssr blur artifacts 2](https://cloud.githubusercontent.com/assets/7585719/7289990/14e2624a-e946-11e4-9945-70a1e88495fa.png)

![kode80 ssr blur artifacts 3](https://cloud.githubusercontent.com/assets/7585719/7290217/53a18cb0-e949-11e4-8507-765dbc8e9b9a.png)

Thank you for your awesome work.

**Comment by jessyoblio** [comment] 2015-04-23 11:07
@astrand130 https://github.com/jessyoblio/kode80SSR... Download the updated code for fix it...

**Comment by kode80** [comment] 2015-04-23 14:24
Spent some time yesterday going over everything and @jessyoblio is correct DepthNormals has nothing to do with this artifact. Since kode80SSR requires the deferred rendering path the _CameraDepthTexture is always available and in fact even if you set the camera's depthMode to DepthNormals or None - everything still works as expected (DepthNormals renders to a separate Sampler2D anyway).
I'm not totally convinced that the current fix is anything but a workaround however. Adding a hardcoded offset to the blur's depth sampling seems to me like it's just raising the threshold of the edge aware blur which might hide these artifacts in specific cases but doesn't actually explain what the issue is.

If everyone that's been experiencing these artifacts could try @jessyoblio's branch out and report back in this thread that'd be helpful. Specifically if a) it fixes the artifacts in your case and b) it still edge-aware blurs correctly (look over-blurring across geometry/ under blurring etc.)

I haven't been able to replicate these artifacts on my machine and a common variable seems to be lots of 3rd party image effects on the camera. I'd like to rule those out as well so if you could try your problem scenes without any effects other than kode80SSR that'd be awesome.

**Comment by jessyoblio** [comment] 2015-04-23 15:43
Hi @kode80! 
Your SSR.Shader works fine...The artifacts problem ( like Astrand130, me, and Snow-Okami) depends on BilateralBlur Shader. I have tried to use SSR without any Post-processing effects... the result don't change... because, for me, it depends on the numbers of the Weights in Bilateral Blur Shader ( Solved )... 

Old Artifacts:
https://imagizer.imageshack.us/v2/1236x636q90/661/tMwG5Q.png

Problem solved:
http://imageshack.com/a/img661/6851/t5p70s.png

Anyway... what you can do for the reflections on the transparent objects?

**Comment by KenzieMac130** [comment] 2015-04-24 00:07
Using jessyoblio's branch has solved this issue for me. also I am noticing that the Screen space reflections do not take advantage of HDR, In some situations someone might have a bright sunlight or flashlight bouncing off a reflective surface but the SSR won't contribute to the additional range and effects like bloom.

Is there a way to fix this or am I setting it up wrong?

**Comment by kode80** [comment] 2015-04-24 12:24
I've pulled and merged the blur fix into the main branch, thanks @jessyoblio! I've also updated the SSR.shader to use smoothness for reflection strength by default instead of metal (which makes more sense and should really have been fixed a while ago).

@astrand130 currently I'm not handling HDR in the reflection buffer, I'll open a new issue for this as a reminder. :)

**Closed as completed** 2015-04-24 12:25 UTC
